# Generated by Django 6.0.1 on 2026-01-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=9, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('birth_date', models.DateField()),
            ],
        ),
    ]
