# Generated by Django 6.0.1 on 2026-01-27 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PEN', 'Pendiente'), ('FIN', 'Finalizada')], default='PEN', max_length=3),
        ),
    ]
