name: Flujo de Integración Continua

# Solo se ejecuta cuando hay un nuevo tag
on:
  push:
    tags:
      - '*'

# Tareas a realizar
jobs:
  build:
    # Se ejecuta sobre un servidor con ubuntu
    runs-on: ubuntu-latest

    steps:
      # Descargar el código en el sistema de github
      - name: Checkout repository
        uses: actions/checkout@v4

      # Identificarse con tus credenciales almacenados en github
      - name: Autenticarse en el registry
        if: github.ref_type == 'tag'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      # Generar la imagen usando docker build .
      # Como la aplicación está en la carpeta clinicapp hay que especificarlo
      - name: Construir imagen
        run: docker build -f clinicapp/Dockerfile -t ghcr.io/gonzalomartinezianez/unidad5-clinica-django:${{ github.ref_name }} clinicapp

      # Subir la imagen al repositorio para que otros la puedan descargar
      # Hay que asegurarse de cambiar la visibilidad a pública desde la web
      - name: Push image
        run: docker push ghcr.io/gonzalomartinezianez/unidad5-clinica-django:${{ github.ref_name }}