name: Flujo de Integración Continua

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Autenticarse en el registry
        if: github.ref_type == 'tag'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Construir imagen
        run: docker build -f clinicapp/Dockerfile -t ghcr.io/gonzalomartinezianez/unidad5-clinica-django:${{ github.ref_name }} clinicapp

      - name: Push image
        run: docker push ghcr.io/gonzalomartinezianez/unidad5-clinica-django:${{ github.ref_name }}